name: ci

on: [pull_request]

permissions:
  contents: read

jobs:
  test:
    runs-on: blacksmith
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          cache: yarn
      - run: yarn install
      - run: yarn lint
      - run: yarn test
  build-ubuntu:
    runs-on: blacksmith
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          cache: yarn
      - uses: useblacksmith/setup-bazel@v2
        with:
          bazelisk-cache: true
          disk-cache: true
          repository-cache: true
          cache-version: 3

      - name: Create bazel cache directory
        run: ls -al ~/.cache
      - run: yarn install
      - run: yarn build
  # build-windows:
  #   runs-on: windows-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         submodules: true
  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version-file: .node-version
  #         cache: yarn
  #     - run: yarn install
  #     - run: yarn build
  #       shell: pwsh
  # build-macos:
  #   runs-on: macos-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         submodules: true
  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version-file: '.node-version'
  #         cache: yarn
  #     - run: yarn install
  #     - run: yarn build
